services:
  mongo:
    image: mongo:6
    ports:
      - 27017:27017
  mariadb:
    image: mariadb:10 # Match major version on Uberspace
    environment:
      - MARIADB_DATABASE=serlo
      - MARIADB_PASSWORD=secret
      - MARIADB_ROOT_PASSWORD=secret
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
