# syntax=docker/dockerfile:1

FROM node:20.15.1
WORKDIR /usr/src/app

RUN apt update && apt install neovim nano -y

COPY . .
RUN yarn install --immutable

RUN yarn build

EXPOSE 3000

ENTRYPOINT ["yarn", "start:dev"]