name: CI Checks
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: yarn lint:eslint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: yarn lint:prettier

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: yarn lint:tsc

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: yarn build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: cp .env.template .env
      - run: yarn install
      - run: yarn build
      - run: yarn dev:databases -d
      # Run `yarn start` in background (otherwise it would block)
      - run: |
          nohup yarn start &
          echo $! > app.pid
      - run: yarn playwright install
      - run: yarn wait-for-server
      - run: HEADLESS=true yarn test
      # End background process
      - run: |
          if [ -f app.pid ]; then
            kill -9 $(cat app.pid) || echo "App already stopped"
          fi
